In [5]:
import numpy as np



In [6]:
5.0/2

2.5

In [7]:
#Takes care of floats
from __future__ import division

In [8]:
# Create array
arr1 = np.array([[1,2,3],[8,9,10]])

#Show
arr1


array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [9]:
# Multiplying Arrays; element-wise multiplication
arr1*arr1

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [10]:
# Subtraction; element-wise subtraction
arr1-arr1

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
#Arithmetic operations with scalars on array
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.125     ,  0.11111111,  0.1       ]])

In [12]:
#Exponential operation
arr1 ** 3

array([[   1,    8,   27],
       [ 512,  729, 1000]])