In [1]:
import numpy as np

In [3]:
my_array = np.array([1,2,3,4,5])

In [4]:
np.save("steve",my_array) # saves with npy extension

In [8]:
steve = np.load("steve.npy")
steve

array([1, 2, 3, 4, 5])

In [13]:
# save zip file
np.savez("ziparray.npz", x = my_array, y = steve)

In [14]:
archive = np.load('ziparray.npz')

In [15]:
archive

In [17]:
archive['x']

array([1, 2, 3, 4, 5])

In [18]:
archive['y']

array([1, 2, 3, 4, 5])